In [31]:
import sys
sys.path.insert(0, '../scripts')

import os
import json
from path import fr1_male_path, fr1_male_sheets, fr1_female_path, fr1_female_sheets, \
                    rev_male_path, rev_male_sheets, rev_female_path, rev_female_sheets

dispense_stats = {}

In [32]:
import pandas as pd
import matplotlib.pyplot as plt
from preprocessing import read_excel_by_sheet
from tools import get_bhv_num

def plot_motor_turn(excel_path, sheet):
    data = pd.read_excel(excel_path, sheet_name=sheet)
    data = data[(data['Event'] == 'Pellet') & (data['Motor_Turns'] > 1)][['Motor_Turns', 'Pellet_Count']]
    exceeding_cnt = int((data['Motor_Turns'] > 15).astype(int).sum())
    # group, num = get_bhv_num(sheet)

    # plt.figure(figsize=(15, 5))
    # plt.bar(data['Pellet_Count'], height=data['Motor_Turns'])
    # plt.axhline(y=15, color='r', linestyle='--', linewidth=2)
    # plt.title(f'Motor Turns Statistics of Run {group} Mouse {num}', fontsize=20)
    # plt.xlabel('Pellet Count', fontsize=16)
    # plt.ylabel('Motor Turns', fontsize=16)

    # threshold_line = plt.Line2D([0], [0], color='red', linestyle='--', linewidth=2, label="Threshold")
    # n_count_text = plt.Line2D([0], [0], color='none', label=f"Exceeding Cnt: {exceeding_cnt}")  # Invisible handle

    # plt.legend(handles=[threshold_line, n_count_text])
    # plt.show()
    return exceeding_cnt, round(exceeding_cnt / len(data), 3)

### FR1 Male

In [33]:
temp_dict = {}
for sheet in fr1_male_sheets[:]:
    cnt, prop = plot_motor_turn(fr1_male_path, sheet)
    temp_dict[sheet] = [cnt, prop]
dispense_stats['FR1_male'] = temp_dict

In [34]:
temp_dict = {}
for sheet in fr1_female_sheets:
    cnt, prop = plot_motor_turn(fr1_female_path, sheet)
    temp_dict[sheet] = [cnt, prop]
dispense_stats['FR1_female'] = temp_dict

In [35]:
temp_dict = {}
for sheet in rev_male_sheets:
    cnt, prop = plot_motor_turn(rev_male_path, sheet)
    temp_dict[sheet] = [cnt, prop]
dispense_stats['rev_male'] = temp_dict

In [36]:
temp_dict = {}
for sheet in rev_female_sheets:
    cnt, prop = plot_motor_turn(rev_female_path, sheet)
    temp_dict[sheet] = [cnt, prop]
dispense_stats['rev_female'] = temp_dict

In [37]:
dispense_stats

{'FR1_male': {'R1M2': [0, 0.0],
  'R1M3': [14, 0.159],
  'R1M4': [0, 0.0],
  'R1M6': [0, 0.0],
  'R1M7': [2, 0.032],
  'R1M8': [0, 0.0],
  'R2M1': [0, 0.0],
  'R2M10': [0, 0.0],
  'R2M11': [1, 0.011],
  'R2M12': [30, 0.203],
  'R2M2': [0, 0.0],
  'R2M3': [0, 0.0],
  'R2M4': [0, 0.0],
  'R2M5': [0, 0.0],
  'R2M6': [11, 0.077],
  'R2M7': [1, 0.022],
  'R2M8': [0, 0.0],
  'R2M9': [14, 0.061]},
 'FR1_female': {'R1M1': [34, 0.315],
  'R1M2': [0, 0.0],
  'R1M3': [23, 0.177],
  'R1M4': [0, 0.0],
  'R1M5': [0, 0.0],
  'R1M6': [0, 0.0],
  'R1M7': [16, 0.533],
  'R1M8': [0, 0.0],
  'R1M9': [2, 0.025],
  'R2M1': [0, 0.0],
  'R2M2': [12, 0.11],
  'R2M3': [0, 0.0],
  'R2M4': [14, 0.095],
  'R2M5': [0, 0.0],
  'R2M6': [0, 0.0]},
 'rev_male': {'R1M2': [0, 0.0],
  'R1M3': [57, 0.393],
  'R1M4': [0, 0.0],
  'R1M5': [0, 0.0],
  'R1M6': [0, 0.0],
  'R1M7': [0, 0.0],
  'R1M8': [0, 0.0],
  'R1M9': [0, 0.0],
  'R2M1': [0, 0.0],
  'R2M10': [2, 0.01],
  'R2M11': [0, 0.0],
  'R2M12': [0, 0.0],
  'R2M2': [0, 0.

In [38]:
with open('../stats/wt_dispense.json', 'w') as f:
    json.dump(dispense_stats, f)

In [53]:
import pickle
import numpy as np
male_acc_dict, female_acc_dict = pickle.load(open('../data/wt_fr1_acc.pkl', 'rb'))
male_dispense_stats, female_dispense_stats = dispense_stats['FR1_male'], dispense_stats['FR1_female']

In [55]:
male_array = []
for key, value in male_acc_dict.items():
    temp = [value]
    temp.extend(male_dispense_stats[key])
    male_array.append(temp)

female_array = []
for key, value in female_acc_dict.items():
    temp = [value]
    temp.extend(female_dispense_stats[key])
    female_array.append(temp)

male_array = np.array(male_array)
female_array = np.array(female_array)

In [58]:
print('Male Correlation Matrix')
print(np.corrcoef(male_array, rowvar=False))
print('Female Correlation Matrix')
print(np.corrcoef(female_array, rowvar=False))

Male Correlation Matrix
[[1.         0.15714504 0.05372283]
 [0.15714504 1.         0.95273684]
 [0.05372283 0.95273684 1.        ]]
Female Correlation Matrix
[[ 1.         -0.05965548 -0.17429808]
 [-0.05965548  1.          0.76136422]
 [-0.17429808  0.76136422  1.        ]]
